# Generated by Django 4.1.7 on 2023-03-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_options_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='voters',
        ),
        migrations.AddField(
            model_name='myuser',
            name='options',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.options'),
        ),
        migrations.AddField(
            model_name='poll',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
